create database if not exists AvailableRoomsDB;

use AvailableRoomsDB;

CREATE TABLE `AVAILABLE_ROOMS` (
  `ROOM_NUMBER` int(11) NOT NULL AUTO_INCREMENT,
  `AIR_CONDITIONING` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`ROOM_NUMBER`)
) 


#below is to insert more columns to a specific table #
ALTER TABLE AVAILABLE_ROOMS
ADD CLIMATE_CONTROL varchar(4),
ADD DVD_PLAYER varchar(4),
ADD WIFI varchar(4),
ADD IN_ROOM_SAFE varchar(4)


#To drop a column#
ALTER TABLE AVAILABLE_ROOMS
DROP COLUMN AIR_CONDITIONING
#Re-adding it as a string with a smaller size#
ALTER TABLE AVAILABLE_ROOMS
ADD AIR_CONDITIONING varchar(4)




INSERT INTO AVAILABLE_ROOMS(ROOM_NUMBER, CLIMATE_CONTROL, DVD_PLAYER, WIFI, IN_ROOM_SAFE, AIR_CONDITIONING)
VALUES('10003', 'No', 'Yes', 'Yes', 'No','No');

ALTER TABLE AVAILABLE_ROOMS
ADD DATE_BOOKED_START DATE,
ADD DATE_BOOKED_END DATE,
ADD BED_TYPE varchar(7),
ADD NUMBER_OF_BEDS int(5),
ADD PRICE_OF_ROOM int(10),
ADD SMOKING varchar(3),
ADD PATIO_VIEW varchar(10),
ADD MINI_FRIDGE varchar(3),
ADD EXTRA_FEATURES varchar(245)

INSERT INTO AVAILABLE_ROOMS(ROOM_NUMBER, CLIMATE_CONTROL, DVD_PLAYER, WIFI, IN_ROOM_SAFE, AIR_CONDITIONING,
DATE_BOOKED_START, DATE_BOOKED_END, BED_TYPE, NUMBER_OF_BEDS, PRICE_OF_ROOM, SMOKING, PATIO_VIEW,
MINI_FRIDGE, EXTRA_FEATURES)
VALUES('10001', 'NO', 'NO', 'YES', 'NO','NO',
'2016-02-1', '2016-02-4', "CA KING", '1', '80.00', 'NO', 'NO', 'YES', 'NONE');


ALTER TABLE AVAILABLE_ROOMS
ADD TRANSACTION_NUMBER int(10)

UPDATE AVAILABLE_ROOMS
SET TRANSACTION_NUMBER = '100003'
WHERE ROOM_NUMBER ='10003'

ALTER TABLE available_rooms
modify TRANSACTION_NUMBER int(10)
after ROOM_NUMBER;

ALTER TABLE available_rooms
modify ROOM_NUMBER int(11)
after TRANSACTION_NUMBER;



